---
version: '3'

services:
  streamlit-financial-tsa:
    container_name: streamlit-financial-tsa
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/streamlit:latest
    ports:
      - 8501:8501
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    environment:
      ALPHAVANTAGE_API_KEY: ${ALPHAVANTAGE_API_KEY}
    entrypoint:
      - /usr/local/bin/streamlit
    command:
      - run
      - app/index.py
      # - --logger.level=info
      - --
      - --debug
